### ISSUE TITLE
upgrade to tf 2.0

### ISSUE THREAD

**Issue by Josh-Joseph** [mit-quest/necstlab-damage-segmentation#44]
This is probably something we should do anyway to keep things usable for the near future but also due to the (mild) security vulnerability in tf 1.15

**Comment by rak5216** [comment]
okay, any changes to current coding that you foresee?

**Comment by Josh-Joseph** [comment]
I'm *hoping* this will only involve changing `tensorflow-gpu = "==1.14"` to `tensorflow-gpu = "*"` in the pipfile but .. here be dragons. so first step would just be to change that line and see if anything breaks (feel free to try it if you have the time otherwise I can get to it soon-ish)

**Comment by rak5216** [comment]
@Josh-Joseph setup vm with `tensorflow-gpu = "*"` and then attempted to to run training code. Following dataset copying, I received the following error:

```
Traceback (most recent call last):
  File "train_segmentation_model.py", line 214, in <module>
    train(**argparser.parse_args().__dict__)
  File "train_segmentation_model.py", line 122, in train
    callbacks=[model_checkpoint_callback, tensorboard_callback, tensorboard_image_callback, csv_logger_callback]
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/keras/engine/training_generator.py", line 100, in fit_generator
    callbacks.set_model(callback_model)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/keras/callbacks/callbacks.py", line 68, in set_model
    callback.set_model(model)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/keras/callbacks/tensorboard_v2.py", line 116, in set_model
    super(TensorBoard, self).set_model(model)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/keras/callbacks.py", line 1532, in set_model
    self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'
```

**Comment by Josh-Joseph** [comment]
Been digging into this -- hit the same error you did. I think this is actually an issue with segmentation models not supporting TF 2 models -- see: https://github.com/qubvel/segmentation_models/issues/231

trying to figure out if/how to fix segmentation models or a possible workaround

**Comment by Josh-Joseph** [comment]
Going to call it a night but I think we can get segmentation models to use tf's keras by setting an enviroment variable -- see: https://github.com/qubvel/segmentation_models/blob/a6fbf2d5ea21081929df634d095d389211e649ef/segmentation_models/__init__.py#L70

Which does (I think) fix this error.

We're also going to likely have to fix the other places we import keras directly rather than tf's keras (and whatever downstream things that'll break).
