### ISSUE TITLE
images output from infer segmentation are broken

### ISSUE THREAD

**Issue by Josh-Joseph** [mit-quest/necstlab-damage-segmentation#54]
Here's an image of the new segmentations from infer:

![image (5)](https://user-images.githubusercontent.com/2060967/74495583-33463c00-4ea6-11ea-8ef0-e988f260b592.png)

And it run for a model pre-tf2 upgrade still produces good images (we're not positive it's a result of the tf2 upgrade but that's the most likely cause at the moment).

**Comment by Josh-Joseph** [comment]
example array output:
```
[[array([[[4.1735876e-02, 3.3571500e-02, 8.3163768e-01],
        [2.1162903e-02, 7.0193154e-03, 9.4948006e-01],
        [1.7072663e-02, 3.4899318e-03, 9.4588715e-01],
        ...,
        [1.7426736e-03, 1.8482386e-03, 9.8505139e-01],
        [2.3415301e-03, 3.2335971e-03, 9.8330253e-01],
        [1.5510220e-02, 2.2896938e-02, 9.1912925e-01]],
       [[1.7760381e-02, 8.6250631e-03, 9.4300157e-01],
        [7.0123365e-03, 1.0009654e-03, 9.9182469e-01],
        [5.1190108e-03, 3.5938597e-04, 9.9258441e-01],
        ...,
        [1.3380592e-04, 1.5223278e-04, 9.9864358e-01],
        [2.2956908e-04, 3.5985769e-04, 9.9840695e-01],
        [3.1946853e-03, 5.2747349e-03, 9.8121637e-01]],
       [[2.1201286e-02, 4.8825205e-03, 9.4653052e-01],
        [1.0431171e-02, 3.6890936e-04, 9.9163753e-01],
        [6.4409762e-03, 1.0636079e-04, 9.9364215e-01],
        ...,
        [1.0380124e-04, 4.8848091e-05, 9.9877471e-01],
        [2.0302838e-04, 1.6238130e-04, 9.9830294e-01],
        [3.0088653e-03, 3.3745652e-03, 9.8102379e-01]],
       ...,
       [[3.7733929e-03, 1.4049895e-03, 9.8234636e-01],
        [1.2169813e-03, 4.3852895e-05, 9.9801081e-01],
        [1.1184104e-03, 7.4537943e-06, 9.9795568e-01],
        ...,
        [1.5184741e-03, 2.9102026e-04, 9.9766964e-01],
        [1.6006549e-03, 7.8668445e-04, 9.9619412e-01],
        [1.1296155e-02, 9.1930814e-03, 9.6889931e-01]],
       [[5.7003316e-03, 3.0882531e-03, 9.7803324e-01],
        [2.1163155e-03, 1.8161055e-04, 9.9692661e-01],
        [2.5430103e-03, 5.0300670e-05, 9.9662232e-01],
        ...,
        [5.0069075e-03, 1.3514644e-03, 9.9466020e-01],
        [4.1150893e-03, 2.1980896e-03, 9.9293172e-01],
        [1.9220559e-02, 1.7265158e-02, 9.6051890e-01]],
```

**Comment by rak5216** [comment]
old model output, from:
```
pipenv run python3 infer_segmentation.py --gcp-bucket gs://necstlab-sandbox --stack-id 8bit_AS4_S2_P1_L6_2560_1750_2160 --model-id segmentation-model-xlarge_esrf16_v2_rand3_3class_20191126T175149Z
```
Predictions:
```
[[array([[[3.22458419e-07, 2.76271024e-08, 1.52708679e-07],
        [1.07552034e-09, 3.76769865e-10, 4.26943508e-10],
        [7.16601389e-10, 2.67297268e-10, 2.54051308e-10],
        ...,
        [2.14542006e-09, 4.25616598e-10, 2.28296471e-09],
        [1.33423033e-08, 2.99157965e-09, 7.44486215e-08],
        [4.90442108e-06, 2.07931021e-06, 2.40694681e-06]],

       [[1.75768233e-10, 9.77545683e-11, 6.98276714e-11],
        [3.01171441e-13, 2.41193486e-13, 1.65562822e-12],
        [1.67776296e-12, 1.65456429e-12, 2.15929392e-11],
        ...,
        [1.03815706e-11, 7.08315481e-12, 7.57295962e-11],
        [2.12237745e-11, 2.02766814e-11, 1.57506919e-09],
        [1.15159651e-08, 7.37075156e-09, 7.71787256e-08]],

       [[1.03003737e-10, 3.74643476e-11, 1.13550745e-10],
        [7.64632064e-13, 6.75144511e-13, 6.04476191e-12],
        [1.23586438e-12, 7.89036534e-13, 8.13375929e-12],
        ...,
        [1.53346294e-11, 4.68513639e-12, 3.27089272e-10],
        [3.43313008e-12, 1.91890731e-12, 1.80741339e-10],
        [2.13838924e-09, 1.26352684e-09, 1.85237781e-08]],

       ...,

       [[3.42440964e-10, 5.47700149e-11, 1.71576420e-10],
        [1.71432616e-12, 1.51410500e-13, 8.61700555e-12],
        [1.41782311e-12, 1.08280057e-13, 2.53260499e-12],
        ...,
        [3.11205142e-12, 1.93708724e-13, 9.53682466e-09],
        [2.46598033e-12, 8.26958456e-13, 2.21220304e-08],
        [2.72798206e-09, 1.09542653e-09, 5.93612754e-07]],

       [[7.65201860e-11, 1.73189050e-11, 6.70758102e-11],
        [1.36957435e-13, 5.36324796e-14, 1.31948028e-13],
        [8.73786517e-14, 2.42877008e-14, 1.59930500e-13],
        ...,
        [5.39202146e-13, 7.20493543e-14, 7.95215671e-10],
        [2.44945476e-13, 1.21736741e-13, 1.75549422e-10],
        [1.27589006e-09, 1.01369935e-09, 3.56787595e-08]],

       [[1.37476675e-07, 3.95656627e-07, 1.75634909e-07],
        [2.48699783e-10, 3.86716104e-10, 9.58137902e-10],
        [1.81401325e-10, 4.19528218e-10, 5.82721704e-10],
        ...,
        [1.08117038e-09, 1.35965517e-09, 1.04311724e-07],
        [7.84531218e-10, 2.19731566e-09, 2.90759790e-08],
        [1.04638184e-06, 1.95290681e-06, 5.59959517e-06]]], dtype=float32), array([[[3.22462711e-07, 2.76274204e-08,
 1.52711593e-07],
        [1.07552856e-09, 3.76777748e-10, 4.26947561e-10],
        [7.16605497e-10, 2.67299793e-10, 2.54053723e-10],
        ...,
        [2.14550200e-09, 4.25640106e-10, 2.28304309e-09],
        [1.33426852e-08, 2.99173930e-09, 7.44510302e-08],
        [4.90450566e-06, 2.07935568e-06, 2.40698569e-06]],

       [[1.75770565e-10, 9.77564418e-11, 6.98291425e-11],
        [3.01177784e-13, 2.41201780e-13, 1.65565977e-12],
        [1.67776296e-12, 1.65459584e-12, 2.15933087e-11],
        ...,
        [1.03823634e-11, 7.08408722e-12, 7.57369584e-11],
```

**Comment by Josh-Joseph** [comment]
okay cool -- so if I'm reading this right the new model looks like it is being normalized to sum to 1 and the old model is not?

**Comment by rak5216** [comment]
the new model doesn't exactly sum to 1, but gets close

**Comment by Josh-Joseph** [comment]
from looking at the numbers I'd guess it is within floating point error -- would it be a pain to print out the sum across that first dimension for the new model?

**Comment by rak5216** [comment]
no prob, i was trying to do similar things yesterday. `sum(pred...`? or numpy gives me axis control if I convert the list to an array?

**Comment by Josh-Joseph** [comment]
easiest is probably to just cast it to a numpy array and then sum -- so something like `np.array(preds).sum(axis=0) (not positive it'll be 0 axis after the cast though)

**Comment by Josh-Joseph** [comment]
(looking at the updated arrays with the sums)

```
 [0.7880012  0.9307665  0.9849142  ... 0.9853697  0.9400189
    0.76434016]]
```
it's real hard to explain a row like this as floating point error. I suppose the next most probable explanation is we either: 
- don't have enough negative images
- are somehow not correctly penalizing false positives

**Comment by rak5216** [comment]
above output from:

```
print('predictions')
print(preds)
print('sum along channels = ')
print(np.sum(preds, axis=-1))
print('size of preds: ')   
print(np.shape(preds)) 
print('size of sum: ')   
print(np.sum(preds, axis=-1).shape)
```

**Comment by Josh-Joseph** [comment]
All right. I think it's that point where we may have to strap ourselves in for another...dig. The next thing to see to start to get to the bottom of this is what happens with just 1 class. Maybe something just of the size of like 2b? Is that an easy thing to start up?

**Comment by rak5216** [comment]
> (looking at the updated arrays with the sums)
> 
> ```
>  [0.7880012  0.9307665  0.9849142  ... 0.9853697  0.9400189
>     0.76434016]]
> ```
> 
> it's real hard to explain a row like this as floating point error. I suppose the next most probable explanations are:
> 
> * don't have enough negative images (so maybe our "smart" cropping caused this?)
> * are somehow not correctly penalizing false positives (so maybe our metric fiddling caused this?)
> * `>1 classes` evaluates metrics differently than just `1 class` (for example, with 1 class keras assumes the other pixels are positive) -- could it be that we just haven't visualized >1 classes lately?

we haven't done 1-class or visualized anything since Dec 2019, before the categ_ce change

**Comment by rak5216** [comment]
will prepare dataset  `dataset-esrf16_segV1_study1_CropCase2_TrnValCaseB_1class.yaml` then train on 100 epochs `train-esrf16_segV1_study1_CropCase2_TrnValCaseB_1class.yaml`. The val and test sets will be similarly sized to train set, and not use the case 6 size.

**Comment by rak5216** [comment]
also trying to replicate an old model (verified to work on tf1) on tf2.1 now:

`pipenv run python3 train_segmentation_model.py --gcp-bucket gs://necstlab-sandbox --config-file configs/config_sandbox/train-xlarge_esrf16_v2_rand1_3class.yaml`

**Comment by rak5216** [comment]
`tf.keras.SparseCategoricalEntropy()` breaks train

```
: logits and labels must have the same first dimension, got logits shape [2097152,3] and labels shape [6291456]
         [[{{node loss/sigmoid_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
         [[metrics/false_pos/assert_less_equal/Assert/AssertGuard/pivot_f/_97/_883]]
2020-02-14 22:30:23.963842: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Invalid argument: logits and labels must have the same first dimension, got logits shape [2097152,3] and labels shape [6291456]
         [[{{node loss/sigmoid_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
  1/358 [..............................] - ETA: 1:39:34WARNING:tensorflow:Can save best model only with loss available, skipping.
Traceback (most recent call last):
  File "train_segmentation_model.py", line 208, in <module>
    train(**argparser.parse_args().__dict__)
  File "train_segmentation_model.py", line 114, in train
    callbacks=[model_checkpoint_callback, tensorboard_callback, csv_logger_callback]
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/rkopp/.local/share/virtualenvs/necstlab-damage-segmentation-wuXG_kFK/lib/python3.5/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  logits and labels must have the same first dimension, got logits shape [2097152,3] and labels shape [6291456]
         [[node loss/sigmoid_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at train_segmentation_model.py:114) ]]
         [[metrics/false_pos/assert_less_equal/Assert/AssertGuard/pivot_f/_97/_883]]
  (1) Invalid argument:  logits and labels must have the same first dimension, got logits shape [2097152,3] and labels shape [6291456]
         [[node loss/sigmoid_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at train_segmentation_model.py:114) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_24132]

Function call stack:
distributed_function -> distributed_function

2020-02-14 22:30:24.333143: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```

**Comment by rak5216** [comment]
Something with tf.keras categorical cross entropy to review, dealing with softmax or not:

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/backend.py#L4487

**Comment by rak5216** [comment]
An issue was found with cat ce and 3-class (no background) in which nothing was learned, then an opposite issue was found with cat ce (normalizes sigmoid as softmax before loss) and 4-class (incl backg) when backg was learned but not dmg, due to the class imbalance of the backg vs dmg. Class imbalance may be an issue in the future with segmenting fibers for example, so it's key to address it now. Class weighting (an improvised approach) did not improve the issue with cat ce. In summary, it was found that the choice of binary ce vs. categorical ce is largely responsible for the model learning issues (infer script is not the problem), and the below results summarize the cases explored that lead to preference of binary ce (sigmoid + binary ce is a **multi-label** problem assuming class independence), so our framing is slightly changed but without losing anything since only highest prob is retained as inference. Main takeaway is binary ce is by far the way to go, need to decide if 3 class or 4 class gives better results?

Some links to guide discussion:
- https://stackoverflow.com/questions/45939446/how-to-build-a-multi-class-convolutional-neural-network-with-keras
- https://forums.fast.ai/t/when-to-use-a-background-or-other-class/52593/2
- https://stackoverflow.com/questions/41455101/what-is-the-meaning-of-the-word-logits-in-tensorflow
- `https://github.com/keras-team/keras/issues/3653`

**Comment by rak5216** [comment]
**CATEGORICAL CROSS ENTROPY MODELS**
- for multi-class classification (mutual exclusivity), pixel can only be one label, cat ce is the proper choice. Ideally, this is the problem we're solving and what the manual annotations correspond to.
- our last layer is sigmoid, but tf2.1 automatically normalizes the sigmoid into a softmax-like fcn before feeding to cat ce loss fcn

**All results below are sample inferences with 8bit_AS4_S2_P1_L6_2560_1750_2160-2089.tif** Colors appear as blue, yellow, red, green for classes 0, 1, 2, 3, respectively.

1.  Models with **3 dmg classes (no background)**, cat ce loss fcn.
- Case 2B (1104 training crops), 50 epochs. 
![image](https://user-images.githubusercontent.com/55461758/74607281-a2d64a00-50a5-11ea-85c5-cadfd5db48a0.png)

- Case 5A (23056 training crops), 100 epochs. 
![image](https://user-images.githubusercontent.com/55461758/74607311-f6e12e80-50a5-11ea-944f-e3aef0d77c22.png)

- Case 6B (55584 training crops), 100 epochs. 
![image](https://user-images.githubusercontent.com/55461758/74607332-22641900-50a6-11ea-9ccb-44e8c765feea.png)


2.  Models with **4 classes (incl. background), no class weighting**, cat ce loss fcn.
- Case 2B expanded with 4th class (1364 training crops), 50 epochs. 
![image](https://user-images.githubusercontent.com/55461758/74607358-5c351f80-50a6-11ea-87de-95c54043b388.png)


3.  Models with **4 classes (incl. background), with class weighting**, cat ce loss fcn. See below for improvised class weighting method.
- Case 2B expanded with 4th class (1364 training crops), 50 epochs. **Background class weight factor = 0.05.** No backg learned.
![image](https://user-images.githubusercontent.com/55461758/74607485-39efd180-50a7-11ea-9472-ee412fa8e12f.png)

- Case 2B expanded with 4th class (1364 training crops), 50 epochs. **Background class weight factor = 0.50.** No backg learned.
![image](https://user-images.githubusercontent.com/55461758/74607533-9226d380-50a7-11ea-88f1-174f55ce48d7.png)

- Case 2B expanded with 4th class (1364 training crops), 50 epochs. **Background class weight factor = 0.90.** No backg learned.
![image](https://user-images.githubusercontent.com/55461758/74607554-c7332600-50a7-11ea-9c6c-c395b8f04b05.png)

- Case 2B expanded with 4th class (1364 training crops), 50 epochs. **Background class weight factor = 0.99.** No backg learned.
![image](https://user-images.githubusercontent.com/55461758/74607558-d6b26f00-50a7-11ea-8db7-824d03586dbf.png)

- Case 2B expanded with 4th class (1364 training crops), 50 epochs. **Background class weight factor = 1.00.** Almost nothing but backg learned, this case is equal to the unweighted case above.
![image](https://user-images.githubusercontent.com/55461758/74607567-e9c53f00-50a7-11ea-88a8-f88d6398fe41.png)



------------------------------------
Class weighting improvisation:

**Comment by rak5216** [comment]
**BINARY CROSS ENTROPY MODELS**
- for multi-label classification (class independence), pixel can only be multiple labels if probabilities above prescribed threshold (we infer with best prob), binary ce is the proper choice for this independence. Possibly, this is like a generalization of the multi-class problem.
- our last layer is sigmoid, and tf2.1 retains the sigmoid value when feeding to binary ce loss fcn

**All results below are sample inferences with 8bit_AS4_S2_P1_L6_2560_1750_2160-2089.tif** Colors appear as blue, yellow, red, green for classes 0, 1, 2, 3, respectively.

------------------------------------

1.  Models with **1 dmg class (no background)**, binary ce loss fcn.
- Case 2B (1104 training crops), 50 epochs. 
![image](https://user-images.githubusercontent.com/55461758/74607845-4b86a880-50aa-11ea-8d42-321ebcb15567.png)

------------------------------------

2.  Models with **3 dmg classes (no background)**, binary ce loss fcn.
- Case 2B (1104 training crops), **50 epochs.** 
![image](https://user-images.githubusercontent.com/55461758/74607880-88eb3600-50aa-11ea-98f1-59327d32aa1f.png)

- Case 2B (1104 training crops), **100 epochs.** 
![image](https://user-images.githubusercontent.com/55461758/74607893-9f918d00-50aa-11ea-9926-54e98c49c18c.png)

------------------------------------

3.  Models with **4 classes (incl. background)**, binary ce loss fcn.
- Case 2B expanded with background class crops (1364 training crops), **50 epochs.** 

with background class overlaid:
![image](https://user-images.githubusercontent.com/55461758/74607925-f6976200-50aa-11ea-9b84-3cf45d427074.png)

same, but with background class not overlaid:
![image](https://user-images.githubusercontent.com/55461758/74607919-ebdccd00-50aa-11ea-926b-cb23ede0fd4e.png)


- Case 2B expanded with background class crops (1364 training crops), **100 epochs.** background class not overlaid.
![image](https://user-images.githubusercontent.com/55461758/74607944-1b8bd500-50ab-11ea-8707-668b897b0571.png)

**Comment by rak5216** [comment]
@Josh-Joseph 

** (ADDITIONAL--NOW THAT BINARY CE IS FOUND BEST) BINARY CROSS ENTROPY MODELS**
_- for multi-label classification (class independence), pixel can only be multiple labels if probabilities above prescribed threshold (we infer with best prob), binary ce is the proper choice for this independence. Possibly, this is like a generalization of the multi-class problem.
- our last layer is sigmoid, and tf2.1 retains the sigmoid value when feeding to binary ce loss fcn
- **main takeaway: binary ce is immune to class imbalance and seems to perform better with all classes present including background**_

**All results below are sample inferences with 8bit_AS4_S2_P1_L6_2560_1750_2160-2089.tif** Colors appear as blue, yellow, red, green for classes 0, 1, 2, 3, respectively.

------------------------------------

1.  Model with **3 dmg classes (no background)**, binary ce loss fcn.
- Case 5B (22,224 training crops = 20X Case 2B), 100 epochs. 

![image](https://user-images.githubusercontent.com/55461758/74769277-2172e900-5258-11ea-9ef7-9222e0661d23.png)

![models_segmentation-model-esrf16_segV1_study1_CropCase5_TrnValCaseB_BinCE_20200216T184331Z_plots_binary_crossentropy](https://user-images.githubusercontent.com/55461758/74769509-8a5a6100-5258-11ea-9a07-0e044d7e9b08.png)

![models_segmentation-model-esrf16_segV1_study1_CropCase5_TrnValCaseB_BinCE_20200216T184331Z_plots_metrics_mosaic](https://user-images.githubusercontent.com/55461758/74769524-8f1f1500-5258-11ea-9954-95c0a1228036.png)

------------------------------------

2.  Model with **3 dmg classes + background class**, binary ce loss fcn.
- Case 5B (22,224 training crops = 20X Case 2B), 100 epochs. Background class not shown.
![image](https://user-images.githubusercontent.com/55461758/74769379-4ebf9700-5258-11ea-9f4d-ebd6d9f5606d.png)

![models_segmentation-model-esrf16_segV1_study1_CropCase5_TrnValCaseB_backgClass_20200217T035438Z_plots_binary_crossentropy](https://user-images.githubusercontent.com/55461758/74769439-672fb180-5258-11ea-96cc-6c7642cd9f5c.png)

![models_segmentation-model-esrf16_segV1_study1_CropCase5_TrnValCaseB_backgClass_20200217T035438Z_plots_metrics_mosaic](https://user-images.githubusercontent.com/55461758/74769446-6a2aa200-5258-11ea-931d-9d8bcd451841.png)

------------------------------------
**Metrics comparison to determine if including background class helps**

**Comment by rak5216** [comment]
excluding background as class is way forward, but must use binary ce
