### ISSUE TITLE
Upgrade python version

### ISSUE THREAD

**Issue by CarolinaFurtado** [mit-quest/necstlab-damage-segmentation#88]
without updating the ubuntu (and cuda versions) because errors with gpu drivers arrise

**Comment by CarolinaFurtado** [comment]
Done, it seems: 

![image](https://user-images.githubusercontent.com/43469359/101082474-81354900-3579-11eb-9c9b-4593201c6173.png)

**Comment by CarolinaFurtado** [comment]
gives out a warning when creating the VM but it is working: 

```
 WARNING: The script easy_install-3.7 is installed in '/home/cfurtado/opt/python-3.7.9/bin' which is not on PATH.
google_compute_instance.vm[5] (remote-exec):   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
google_compute_instance.vm[5] (remote-exec):   WARNING: The scripts pip3 and pip3.7 are installed in '/home/cfurtado/opt/python-3.7.9/bin' which is not on PATH.
google_compute_instance.vm[5] (remote-exec):   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

```

**Comment by CarolinaFurtado** [comment]
# Ingest data gives an error in the end

```
 Ingest Raw Data Metadata:
{'elapsed_minutes': 3.8, 'images': {'created_datetime': '20191130T033137Z', 'gcp_bucket': 'gs://necstlab-sandbox', 'git_hash': '268d6d0913bafab6b466bb1b23091b0787b7f2d0', 'number_of_imag
es': 5440, 'original_number_of_files_in_zip': 5440, 'zipped_stack_file': 'gs://necstlab-sandbox/raw-data/RAK_OHC_RT50RH_Bat2Base1_BE79_L1_3068_2240_5440.7z'}, 'annotations': {'gcp_bucket
': 'gs://necstlab-sandbox', 'zipped_stack_file': 'gs://necstlab-sandbox/raw-data/RAK_OHC_RT50RH_Bat2Base1_BE79_L1_3068_2240_5440-dmg_labels_GV.7z', 'created_datetime': '20201203T204413Z'
, 'original_number_of_files_in_zip': 5440, 'number_of_images': 5440, 'git_hash': '81821ebf48940b6ad126c1545084a6d66306e2b4'}}
Traceback (most recent call last):
  File "ingest_raw_data.py", line 132, in <module>
    process_zips(gcp_bucket=kw_args['gcp_bucket'])
  File "ingest_raw_data.py", line 22, in process_zips
    process_zip(gcp_bucket, os.path.join(gcp_bucket, zipped_stack))
  File "ingest_raw_data.py", line 109, in process_zip
    shutil.rmtree(tmp_directory.as_posix())
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 432, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/cfurtado/opt/python-3.7.9/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '8bit_AS4_S2_P1_L6_2560_1750_2160_dmg_labels_GV0134.tif_.gstmp'
```
